### ISSUE TITLE
Broken archive?

### ISSUE THREAD

**Issue by yakimovsa** [ruslan-corpus/ruslan-corpus.github.io#4]
I tried to download dataset archive several times, but still no luck with unpacking it. Could you please check the archive?

**Comment by morelen17** [comment]
Hi, @yakimovsa! Sure.

**Comment by morelen17** [comment]
@yakimovsa, which tool do you use to unpack the archive?

This worked for me:
```
# cd to folder w/ the archive
mkdir ./ruslan-corpus/
unzip RUSLAN.zip -d ./ruslan-corpus/
```

**Comment by yakimovsa** [comment]
The problem was with my archive manager. Thank you!

**Comment by kephome** [comment]
> @yakimovsa, which tool do you use to unpack the archive?
> 
> This worked for me:
> 
> ```
> # cd to folder w/ the archive
> mkdir ./ruslan-corpus/
> unzip RUSLAN.zip -d ./ruslan-corpus/
> ```

In my case it says:
```
Archive:  RUSLAN.zip
warning [RUSLAN.zip]:  4294967296 extra bytes at beginning or within zipfile
  (attempting to process anyway)
file #1:  bad zipfile offset (local header sig):  4294967296
  (attempting to re-compensate)
   creating: ./ruslan-corpus/RUSLAN/
error: invalid zip file with overlapped components (possible zip bomb)
```

**Comment by asarsembayev** [comment]
> mkdir ./ruslan-corpus/
> unzip RUSLAN.zip -d ./ruslan-corpus/

Try with
`7z e RUSLAN.zip`

[reference](https://unix.stackexchange.com/questions/634315/unzip-thinks-my-zip-file-is-a-zip-bomb)

**Comment by dfmordol** [comment]
> > @yakimovsa, which tool do you use to unpack the archive?
> > This worked for me:
> > ```
> > # cd to folder w/ the archive
> > mkdir ./ruslan-corpus/
> > unzip RUSLAN.zip -d ./ruslan-corpus/
> > ```
> 
> In my case it says:
> 
> ```
> Archive:  RUSLAN.zip
> warning [RUSLAN.zip]:  4294967296 extra bytes at beginning or within zipfile
>   (attempting to process anyway)
> file #1:  bad zipfile offset (local header sig):  4294967296
>   (attempting to re-compensate)
>    creating: ./ruslan-corpus/RUSLAN/
> error: invalid zip file with overlapped components (possible zip bomb)
> ```

In my case to

**Comment by morelen17** [comment]
@kephome @dfmordol 
This error may be related to `unzip` bug -- https://access.redhat.com/discussions/5171931.
Please, try using different archive manager apps to unzip the file.

**Comment by morelen17** [comment]
@kephome @dfmordol 
Добавили `tar.gz` архив

**Comment by kephome** [comment]
> @kephome @dfmordol Добавили `tar.gz` архив

Благодарю!
