### ISSUE TITLE
А как это заставить работать, если я не программист?

### ISSUE THREAD

**Issue by mikuskov** [ruslan-corpus/ruslan-corpus.github.io#5]
Здравствуйте.
Я долго и добросовестно качал архив с "Русланом", но что с ним делать? Вот у меня есть программа типа "Балаболка" и я туда установил несколько движков. Скачал их, кликнул, установил. Всё просто и понятно. А как слушать "Руслана" на десктопе под Windows 8.1, если я не владею языками программирования, не администратор сервера и т.д.?

**Comment by morelen17** [comment]
Здравствуйте, @mikuskov!
"РусЛан" - это датасет (набор данных - пары <текст, аудио>), собранный нашей командой, для тренировки алгоритмов машинного обучения перевода текста в речь (text-to-speech, TTS), или речи в текст (automatic speech recognition, ASR), или др. задач. "РусЛан" _не включает_ в себя какое-либо ПО для воспроизведения аудио, обучения моделей или генерации речи.

**Comment by mikuskov** [comment]
Спасибо за ответ!
