### ISSUE TITLE
Подходит Ваш корпус для обучения Tortoise? 

### ISSUE THREAD

**Issue by dreamfaceprod** [ruslan-corpus/ruslan-corpus.github.io#6]
Добрый день! 
Меня зовут Владимир, команда "DreamFace"
Мы с командой несколько месяцев пытаемся получить достойный Tortoise на русском языке

**Comment by morelen17** [comment]
Здравствуйте, @dreamfaceprod!

Вы про [https://github.com/neonbjb/tortoise-tts](https://github.com/neonbjb/tortoise-tts)?
