### ISSUE TITLE
Какую архитектуру вы тренировали на своем корпусе?

### ISSUE THREAD

**Issue by asarsembayev** [ruslan-corpus/ruslan-corpus.github.io#7]
Был ли это Tacotron2 или FastSpeech2? Или же какая-то другая архитектура?

**Comment by morelen17** [comment]
@asarsembayev 
Привет! Мы тренировали Tacotron с некоторыми архитектурными изменениями.

**Comment by gohoski** [comment]
Можете ли вы поделиться данными изменениями, особенно для работы в Google Colab? Буду очень благодарен!

**Comment by morelen17** [comment]
@gohoski 

1. Заменили GRU на LayerNorm-LSTM
2. Заменили Griffin-Lim algorithm на Fast Griffin-Lim

Другие подробности Вы сможете найти в статье - https://arxiv.org/abs/1906.11645
