### ISSUE TITLE
7z формат

### ISSUE THREAD

**Issue by elapteff** [ruslan-corpus/ruslan-corpus.github.io#8]
Не могу разархивировать Ruslan.zip пишет что неверный формат. WinZip говорит что главный каталог не найден

**Comment by morelen17** [comment]
@elapteff привет!
Пожалуйста, попробуйте воспользоваться другим архиватором.

Если ничего не поможет, переоткройте issue, напишите сообщение, и мы перезальём архив и оповестим вас. Спасибо!

**Comment by morelen17** [comment]
@elapteff 
Добавили `tar.gz` архив
